# Generated by Django 6.0.3 on 2026-04-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_stripe", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPayment",
        ),
    ]
